services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: 'mysqladmin'
      MYSQL_PASSWORD: 'mysqladmin123'
      MYSQL_DATABASE: 'mydailydiet'
      MYSQL_ROOT_PASSWORD: 'mysqladmin'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - /home/brcds/dev/daily-diet-api/mysql:/var/lib/mysql