services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin123'
      MYSQL_DATABASE: 'my-daily-diet'
      MYSQL_ROOT_PASSWORD: 'admin123'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - /home/brcds/dev/daily-diet-api/mysql:/var/lib/mysql