services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: 'mysqladmin'
      MYSQL_PASSWORD: 'mysqladmin123'
      MYSQL_DATABASE: 'mydailydiet'
      MYSQL_ROOT_PASSWORD: 'mysqladmin'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./mysql:/var/lib/mysql

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file: .env
    command: [ "flask", "run", "--host=0.0.0.0" ]

  tests:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
    env_file: .env.testing
    command: [ "pytest", "tests.py" ]